name: Misspelled Nemesis Club
description: Blogging about stuffs

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
permalink:      'blog/:year/:month/:day/:title.html'
domain_name:    'https://moreati.github.io'

gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://moreati.github.io'
author:         'Alex Willmer'
